name: CI/CD for Ansible Playbook (Dev)

on:
  push:
    branches:
      - dev

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Setup Script
      run: |
        chmod +x setup.sh
        ./setup.sh

    - name: Decrypt Ansible Vault File
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt
        ansible-vault decrypt environments/dev/org_admin_credentials.yml --vault-password-file vault_pass.txt

    - name: List Files in Playbooks Directory
      run: |
        ls -la playbooks

    - name: Run Ansible Playbook
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      run: |
        ansible-playbook -i inventory/dev/hosts playbooks/configure_org.yml --vault-password-file vault_pass.txt

